#!/usr/bin/php
<?php
echo "Determining most recent SVN revision...\r\n";
try {
	$changelog = @file_get_contents( 'http://plugins.trac.wordpress.org/log/?format=changelog&stop_rev=HEAD' );
	if ( !$changelog )
		throw new Exception( 'Could not fetch the SVN changelog' );
	preg_match( '#\[([0-9]+)\]#', $changelog, $matches );
	if ( !$matches[1] )
		throw new Exception( 'Could not determine most recent revision.' );
} catch ( Exception $e ) {
	die( $e->getMessage() . "\r\n" );
}
$svn_last_revision = (int) $matches[1];
echo "Most recent SVN revision: " . $svn_last_revision . "\r\n";
if ( file_exists( 'plugins/.last-revision' ) ) {
	$last_revision = (int) file_get_contents( 'plugins/.last-revision' );
	echo "Last synced revision: " . $last_revision . "\r\n";
} else {
	$last_revision = false;
	echo "You have not yet performed a successful sync. Settle in. This will take a while.\r\n";
}

$start_time = time();

if ( $last_revision != $svn_last_revision ) {
	if ( $last_revision ) {
		$changelog_url = sprintf( 'http://plugins.trac.wordpress.org/log/?verbose=on&mode=follow_copy&format=changelog&rev=%d&limit=%d', $svn_last_revision, $svn_last_revision - $last_revision );
		$changes = file_get_contents( $changelog_url );
		preg_match_all( '#^' . "\t" . '*\* ([^/A-Z ]+)[ /].* \((added|modified|deleted|moved|copied)\)' . "\n" . '#m', $changes, $matches );
		$plugins = array_unique( $matches[1] );
	} else {
		$plugins = file_get_contents( 'http://svn.wp-plugins.org/' );
		preg_match_all( '#<li><a href="([^/]+)/">([^/]+)/</a></li>#', $plugins, $matches );
		$plugins = $matches[1];
	}
	
    foreach ( $plugins as $plugin ) {
		$plugin = urldecode( $plugin );
		echo "Updating " . $plugin . "\r\n";
		exec( 'wget -q -np -O ' . escapeshellarg( 'zips/' . $plugin . '.zip' ) . ' ' . escapeshellarg( 'http://downloads.wordpress.org/plugin/' . $plugin . '.zip' ) . ' > /dev/null' );
		if ( file_exists( 'plugins/' . $plugin ) ) {
            exec( 'rm -rf ' . escapeshellarg( 'plugins/' . $plugin ) );
        }

        if ( file_exists( 'zips/' . $plugin . '.zip' ) ) {
            exec( 'unzip -d plugins ' . escapeshellarg( 'zips/' . $plugin . '.zip' ) );
			exec( 'rm -rf ' . escapeshellarg( 'zips/' . $plugin . '.zip' ) );
		}

    }

	if ( file_put_contents( 'plugins/.last-revision', $svn_last_revision ) )
		echo "[CLEANUP] Updated plugins/.last-revision to " . $svn_last_revision . "\r\n";
	else
		echo "[ERROR] Could not update plugins/.last-revision to " . $svn_last_revision . "\r\n";
}

$end_time = time();
$minutes = ( $end_time - $start_time ) / 60;
$seconds = ( $end_time - $start_time ) % 60;

echo "[SUCCESS] Done updating plugins!\r\n";
echo "It took " . number_format($minutes) . " minutes and " . $seconds . " seconds to update ". count($plugins)  ." plugins\r\n";
echo "[DONE]\r\n";
